security:
  # Configuration des méthodes de hachage des mots de passe
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # Définition du fournisseur de l'utilisateur
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Configuration des pare-feux
  firewalls:
    # Pare-feu pour l'environnement de développement
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Pare-feu principal
    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\UsersAuthentificatorAuthenticator
      logout:
        path: app_logout
        # where to redirect after logout
        # target: app_any_route

      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800
        path: /
        always_remember_me: true

    # Nouveau pare-feu pour la route "avis-clients"
    avis_clients:
      pattern: ^/avis-clients
      security: false

  access_control:
    # Exiger le rôle ROLE_ADMIN pour accéder à /admin
    - { path: ^/admin, roles: ROLE_ADMIN }

    # Exiger le rôle ROLE_SUPER_ADMIN pour accéder à /super-admin
    - { path: ^/super-admin, roles: ROLE_SUPER_ADMIN }
