controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

uploads_cars:
  path: /uploads/Cars/{filename}
  controller: App\Controller\CarController::uploadsCars

app_reviews:
  path: /avis-clients
  controller: 'App\Controller\ReviewsController::index'
  methods: [GET, POST]
